apiVersion: apps/v1
kind: Deployment
metadata:
  name: autograph-strapi
  namespace: autograph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autograph-strapi
  template:
    metadata:
      labels:
        app: autograph-strapi
    spec:
      containers:
        - name: strapi
          image: 202662063830.dkr.ecr.us-east-1.amazonaws.com/autograph-strapi:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"
            - name: APP_KEYS
              value: "key1,key2,key3,key4"
            - name: JWT_SECRET
              value: "jwtsecret123"
            - name: ADMIN_JWT_SECRET
              value: "adminjwtsecret123"
            - name: ADMIN_AUTH_SECRET
              value: "adminauthsecret123"
            - name: API_TOKEN_SALT
              value: "apitokensalt123"

          volumeMounts:
            - name: uploads
              mountPath: /opt/app/public/uploads

      volumes:
        - name: uploads
          emptyDir: {}

